export const CHART_DATA_LOADING_START = "CHART_DATA_LOADING_START";
export const CHART_DATA_LOADING_FAILURE = "CHART_DATA_LOADING_FAILURE";
export const CHART_DATA_LOADING_SUCCESS = "CHART_DATA_LOADING_SUCCESS";
